routes/web.php
<?php

use App\Constants\AuthorizationModule;
use App\Http\Controllers\KonfigurasiController;
use App\Http\Controllers\Laporan\LaporanRpjmdController;
use App\Http\Controllers\Laporan\LaporanRenstraController;
use App\Http\Controllers\Laporan\PerjanjianKinerjaController;
use App\Http\Controllers\Mst\BidangUrusanController;
use App\Http\Controllers\Mst\OpdController;
use App\Http\Controllers\Mst\PeriodeController;
use App\Http\Controllers\Mst\UrusanController;
use App\Http\Controllers\Mst\SatuanController;
use App\Http\Controllers\Mst\ProgramController;
use App\Http\Controllers\Mst\KegiatanController;
use App\Http\Controllers\Mst\SubKegiatanController;
use App\Http\Controllers\Mst\SumberAnggaranController;
use App\Http\Controllers\Mst\PrioritasPembangunanController;
use App\Http\Controllers\Mst\PegawaiController;
use App\Http\Controllers\Mst\EselonController;
use App\Http\Controllers\Mst\PangkatController;
use App\Http\Controllers\Mst\PangkatGolonganController;
use App\Http\Controllers\PerjanjianKinerja\AnggaranKegiatanController;
use App\Http\Controllers\PerjanjianKinerja\AnggaranProgramController;
use App\Http\Controllers\PerjanjianKinerja\AnggaranSubKegiatanController;
use App\Http\Controllers\PerjanjianKinerja\IndikatorKegiatanController;
use App\Http\Controllers\PerjanjianKinerja\IndikatorProgramController;
use App\Http\Controllers\PerjanjianKinerja\IndikatorSasaranController;
use App\Http\Controllers\PerjanjianKinerja\OutputSubKegiatanController;
use App\Http\Controllers\PerjanjianKinerja\PkRenjaTahunanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Renstra\TujuanRenstraController;
use App\Http\Controllers\Renstra\SasaranRenstraController;
use App\Http\Controllers\Renstra\StrategiRenstraController;
use App\Http\Controllers\Renstra\KebijakanRenstraController;
use App\Http\Controllers\Renstra\Kegiatan\KegiatanRenstraController;
use App\Http\Controllers\Renstra\Kegiatan\PenanggungJawabKegiatanController;
use App\Http\Controllers\Renstra\Kegiatan\SasaranKegiatanController;
use App\Http\Controllers\Renstra\Program\PenanggungJawabController;
use App\Http\Controllers\Renstra\Program\SasaranProgramController;
use App\Http\Controllers\Renstra\ProgramRenstraController;
use App\Http\Controllers\Renstra\Sasaran\PenanggungJawabSasaranRenstraController;
use App\Http\Controllers\Renstra\SubKegiatan\PenanggungJawabSubKegiatanController;
use App\Http\Controllers\Renstra\SubKegiatan\SasaranSubKegiatanController;
use App\Http\Controllers\Renstra\SubKegiatan\SubKegiatanController as SubKegiatanSubKegiatanController;
use App\Http\Controllers\Rpjmd\KebijakanRpjmdController;
use App\Http\Controllers\Rpjmd\MisiController;
use App\Http\Controllers\Rpjmd\PrioritasPembangunanRpjmdController;
use App\Http\Controllers\Rpjmd\Program\IndikatorProgramRpjmdController;
use App\Http\Controllers\Rpjmd\Program\ProgramRpjmdController;
use App\Http\Controllers\Rpjmd\Program\SumberAnggaranRpjmdController;
use App\Http\Controllers\Rpjmd\Program\PenanggungJawabRpjmdController;
use App\Http\Controllers\Rpjmd\SasaranController;
use App\Http\Controllers\Rpjmd\StrategiRpjmdController;
use App\Http\Controllers\Rpjmd\VisiController;
use App\Http\Controllers\Rpjmd\TujuanController;
use App\Http\Controllers\SyncRestfulApiController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

require __DIR__ . '/auth.php';
Route::middleware(['auth'])->group(function () {
    Route::get('/', function () {
        return view('dashboard');
    });

    Route::prefix('profile/change-password')->name('profile.change_password.')->group(function () {
        Route::get('/')->name('index')->uses([ProfileController::class, 'changePasswordIndex']);
        Route::post('/')->name('update')->uses([ProfileController::class, 'changePasswordUpdate']);
    });

    Route::get('/dashboard', function () {
        return view('dashboard');
    });

    Route::middleware('access_module:' . AuthorizationModule::MASTER)->group(function () {
        Route::prefix('periode')->group(function () {
            Route::get('/', [PeriodeController::class, 'index']);
            Route::post('/add', [PeriodeController::class, 'store']);
            Route::delete('/{id}/delete', [PeriodeController::class, 'destroy']);
            Route::patch('/{id}/edit', [PeriodeController::class, 'update']);
        });

        Route::prefix('opd')->group(function () {
            Route::get('/', [OpdController::class, 'index']);
            Route::post('/add', [OpdController::class, 'store']);
            Route::delete('/{id}/delete', [OpdController::class, 'destroy']);
            Route::patch('/{id}/edit', [OpdController::class, 'update']);
        });

        Route::prefix('satuan')->group(function () {
            Route::get('/', [SatuanController::class, 'index']);
            Route::post('/add', [SatuanController::class, 'store']);
            Route::delete('/{id}/delete', [SatuanController::class, 'destroy']);
            Route::patch('/{id}/edit', [SatuanController::class, 'update']);
        });

        Route::prefix('urusan')->group(function () {
            Route::get('/', [UrusanController::class, 'index']);
            Route::post('/add', [UrusanController::class, 'store']);
            Route::delete('/{id}/delete', [UrusanController::class, 'destroy']);
            Route::patch('/{id}/edit', [UrusanController::class, 'update']);
        });

        Route::prefix('bidang-urusan')->group(function () {
            Route::get('/', [BidangUrusanController::class, 'index']);
            Route::post('/add', [BidangUrusanController::class, 'store']);
            Route::delete('/{id}/delete', [BidangUrusanController::class, 'destroy']);
            Route::patch('/{id}/edit', [BidangUrusanController::class, 'update']);
        });

        Route::prefix('program')->group(function () {
            Route::get('/', [ProgramController::class, 'index']);
            Route::post('/add', [ProgramController::class, 'store']);
            Route::delete('/{id}/delete', [ProgramController::class, 'destroy']);
            Route::patch('/{id}/edit', [ProgramController::class, 'update']);
        });

        Route::prefix('kegiatan')->group(function () {
            Route::get('/', [KegiatanController::class, 'index']);
            Route::post('/add', [KegiatanController::class, 'store']);
            Route::delete('/{id}/delete', [KegiatanController::class, 'destroy']);
            Route::patch('/{id}/edit', [KegiatanController::class, 'update']);
            Route::get('/datatable-kegiatan', [KegiatanController::class, 'datatableKegiatan'])->name('kegiatan.index');
        });

        Route::prefix('sub-kegiatan')->group(function () {
            Route::get('/', [SubKegiatanController::class, 'index']);
            Route::post('/add', [SubKegiatanController::class, 'store']);
            Route::delete('/delete/{id}', [SubKegiatanController::class, 'destroy']);
            Route::patch('/edit/{id}', [SubKegiatanController::class, 'update']);
            Route::get('/datatable-sub-kegiatan', [SubKegiatanController::class, 'datatableSubKegiatan']);
        });

        Route::prefix('sumber-anggaran')->group(function () {
            Route::get('/', [SumberAnggaranController::class, 'index']);
            Route::post('/add', [SumberAnggaranController::class, 'store']);
            Route::delete('/{id}/delete', [SumberAnggaranController::class, 'destroy']);
            Route::patch('/{id}/edit', [SumberAnggaranController::class, 'update']);
        });

        Route::prefix('prioritas-pembangunan')->group(function () {
            Route::get('/', [PrioritasPembangunanController::class, 'index']);
            Route::post('/add', [PrioritasPembangunanController::class, 'store']);
            Route::delete('/{id}/delete', [PrioritasPembangunanController::class, 'destroy']);
            Route::patch('/{id}/edit', [PrioritasPembangunanController::class, 'update']);
        });

        Route::prefix('pegawai')->group(function () {
            Route::get('/', [PegawaiController::class, 'index']);
            Route::get('/datatable-pegawai', [PegawaiController::class, 'datatablePegawai']);
        });

        Route::prefix('eselon')->group(function () {
            Route::get('/', [EselonController::class, 'index']);
        });

        Route::prefix('pangkat')->group(function () {
            Route::get('/', [PangkatController::class, 'index']);
        });

        Route::prefix('pangkat-golongan')->group(function () {
            Route::get('/', [PangkatGolonganController::class, 'index']);
        });
    });

    Route::middleware('access_module:' . AuthorizationModule::RPJMD)->name('rpjmd.')->group(function () {

        Route::prefix('visi')->group(function () {
            Route::get('/', [VisiController::class, 'index']);
            Route::post('/add', [VisiController::class, 'store']);
        });

        Route::prefix('misi')->group(function () {
            Route::get('/', [MisiController::class, 'index']);
            Route::post('/add', [MisiController::class, 'store']);
            Route::get('/delete/{id}', [MisiController::class, 'destroy']);
        });

        Route::prefix('tujuan')->group(function () {
            Route::get('/', [TujuanController::class, 'index']);
            Route::get('/add', [TujuanController::class, 'create']);
            Route::post('/store', [TujuanController::class, 'store']);
            Route::get('/edit/{id}', [TujuanController::class, 'edit']);
            Route::patch('/{id}/update', [TujuanController::class, 'update']);
            Route::delete('/{id}/delete', [TujuanController::class, 'destroy']);
            Route::get('/{id}/delete-indikator', [TujuanController::class, 'destroyIndikator']);
        });

        Route::prefix('sasaran')->name('sasaran.')->group(function () {
            Route::get('/', [SasaranController::class, 'index']);

resources/views/dashboard.blade.php
@extends('layouts.app')
@section('title')
Dashboard
@endsection
@section('content')
<style media="screen">
.modal-lg {
    width: 750px !important;
}
.text-kiri{
    text-align: left;
}
</style>
<div class="col-12">
    <div class="br-pageheader pd-y-15 pd-l-20" style="background-color: #fff; box-shadow: 1px 1px 1px rgba(0,0,0,.1)">
        <span class="brand ml-4">Dashboard</span>
        <nav class="mr-4">
            <a class="breadcrumb-item" href="/">Dashboard</a>
        </nav>
    </div>
</div>

<div class="container-fluid pb-2 mt-4">
    <div class="card shadow-base pb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card-header">
                        <p class="text-dark">Selamat Datang.</p>
                    </div>
                    <div class="container">
                            <table class="table table-bordered table-hove">
                                <thead>
                                    <tr>
                                        <td class="text-dark">Username</td>
                                        <td class="text-center text-dark">:</td>
                                        <td style="text-align: left;">{{ Auth::user()->username }}</td>
                                    </tr>
                                    <tr>
                                        <td class="text-dark">Nama</td>
                                        <td class="text-center text-dark">:</td>
                                        <td style="text-align: left;">{{ Auth::user()->name }}</td>
                                    </tr>
                                    <tr>
                                        <td class="text-dark">Role</td>
                                        <td class="text-center text-dark">:</td>
                                        <td style="text-align: left;">{{ Auth::user()->role }}</td>
                                    </tr>
                                </thead>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ganti-password.blade.php
@extends('layouts.app')
@section('title')
    Ganti Password
@endsection
@section('content')

<div class="br-pageheader pd-y-15 pd-l-20" style="background-color: #fff; box-shadow: 1px 1px 1px rgba(0,0,0,.1)">
    <span class="brand ml-4">Administrator</span>
    <nav class="mr-4">
        <a class="breadcrumb-item" href="/">Profile</a>
        <span class="breadcrumb-item" style="color: #000;">Ganti Password</span>
    </nav>
</div>
<div class="container-fluid pb-2 mt-4">
    <div class="card shadow-base pb-3">
        <div class="card-header">
            <h6>Ganti Password</h6>
            <a href="{{ route('users.create') }}">
                <button class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Tambah</button>
            </a>
        </div>
        <form action="{{ route('profile.change_password.update') }}" method="POST">
            <div class="card-body">
                @include('partials.error-message')
                @include('partials.message')
                @csrf
                <div class="input-group input-group-outline">
                    <div class="col-4">
                        <label for="old_password">Password Lama</label>
                        <input
                            type="password"
                            id="old_password"
                            class="form-control"
                            name="old_password">
                    </div>
                </div>
                <div class="input-group input-group-outline">
                    <div class="col-4">
                        <label for="password">Password baru</label>
                        <input
                            type="password"
                            id="password"
                            class="form-control"
                            name="password">
                    </div>
                </div>
                <div class="input-group input-group-outline">
                    <div class="col-4">
                        <label for="password_confirmation">Konfirmasi Password baru</label>
                        <input
                            type="password"
                            id="password_confirmation"
                            class="form-control"
                            name="password_confirmation">
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-dark cancel" onclick="return window.history.back()" type="button">Cancel</button>
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>

    </div>
</div>
@endsection

resources/views/konfigurasi.blade.php
@extends('layouts/app')
@section('title')
    Konfigurasi
@endsection
@section('content')

<style media="screen">
    .modal-lg{
      width: 750px !important;
    }
  </style>
  
  <div class="br-pageheader pd-y-15 pd-l-20" style="background-color: #fff; box-shadow: 1px 1px 1px rgba(0,0,0,.1)">
      <span class="brand ml-4">Set Periode</span>
      <nav class="mr-4">
          <a class="breadcrumb-item" href="/">Dashboard</a>
          <a class="breadcrumb-item" href="#">Konfigurasi</a>
          <span class="breadcrumb-item" style="color: #000;">Set Periode</span>
      </nav>
  </div>
  
  <div class="container-fluid pb-2 mt-4">
    <div class="card">
        @if ($message = Session::get('selected'))
        <div class="alert alert-success flashMessages" role="alert">
            {{ $message }}
        </div>
        @endif

        @if(!is_null($periode->first()))
        <div class="card-header">
            <table>
                <tr>
                    <td><h6>Periode saat ini</td>
                    <td><h6>&emsp;:&emsp;</h6></td>
                    @if(!is_null(periode()))
                    <td><h6>{{ periode()->nama }} ({{ periode()->dari }} - {{ periode()->sampai }})</h6></td>
                    @else
                    <td><h6 class="text-danger">Periode Belum di set!</h6></td>
                    @endif
                </tr>
            </table>
        </div>
        <div class="card-body">
            <div class="col-sm-4">
                <form action="{{ url('') }}/konfigurasi/set" method="POST">
                    @csrf
                    <div class="input-group input-group-outline">
                        <label for="periode">Periode * :</label>
                        <select name="periode" class="periode">
                            <option value=""></option>
                            @foreach ($periode as $item)
                            <option value="{{ $item->id }}">{{ $item->nama }} ({{ $item->dari }} - {{ $item->sampai }})</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="input-group input-group-outline">
                        <button type="submit" class="btn btn-primary btn-sm">Set Periode</button>
                    </div>
                </form>
            </div>
        </div>
        @else
        <h6 class="text-danger">Isi data periode terlebih dahulu!</h6>
        <a href="{{ url('/periode') }}" class="btn btn-primary btn-sm mt-3">Tambah periode</a>
        @endif
    </div>
  </div>
@endsection

@section('scripts')
  <script>
      selectPlaceholder('.periode', 'Pilih Periode');
  </script>
@endsection